### ISSUE TITLE
reduce number of events on a PR

### ISSUE THREAD

**Issue by Borda** [python-cachier/cachier#146]
@shaypal5 would it be possible to reduce the number of events in the PR? It is super long, and GH hides all intermediate comments, so the PR is much harder to follow... :confused: 
![image](https://github.com/python-cachier/cachier/assets/6035284/c3d565ec-c872-41c5-bb2a-d88376b9557d)

**Comment by shaypal5** [comment]
I agree.

The current matricization of the the test job across different platforms make Github consider them as separate checks, which is what has been annoying us all in PR conversations.

The upside is that all such builds run in parallel.

We should take this into consideration when suggesting an alternative; perhaps this can be collapsed somehow just for the conversation view's sake.

**Comment by Borda** [comment]
> The upside is that all such builds run in parallel.

I run several small/large projects also with numerous parallelization and interdependency but never say this, so really not sure what the root is :confused: 

> The current matricization of the test job across different platforms make Github consider them as separate checks, which is what has been annoying us all in PR conversations.

My suspicion would be that it is because of this line:
https://github.com/python-cachier/cachier/blob/81f56c87a1466ef35312e514696cef0207b09d24/.github/workflows/test.yml#L14

**Comment by shaypal5** [comment]
Ok.

We do need it, though, to get the secrets that connect to MongoDB.

Even if we transition to a local one, I want us to know how to work with repo-level environments which grant access to repo secrets.

Maybe just the level of nesting? Let's find other such YAMLs using the environment key.

**Comment by shaypal5** [comment]
See the reference use in [Github documentation](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment):
```yaml
name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com
    steps:
      - name: deploy
        # ...deployment-specific steps
```

VS our use:
```yaml
name: Test

on:
  push:
  pull_request:
  schedule:
     # * is a special character in YAML so you have to quote this string
     # min hours day(month) month day(week)
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    environment:
      name: test
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        backend: ['local', 'db']
```

**Comment by Borda** [comment]
Yes, and what I [read](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-secrets) some time ago, the environment this meant to aggregate secrets and other sensitive information, but in the testing, you set the secrets explicitly anyway so I gues it does not have any positive effect... see suggestion in #154

**Comment by shaypal5** [comment]
I do not set the secrets explicitly, I just forward them from the Github environment into the the node running the test as environment variables on that (probably virtual/containerized) machine.

```yaml
 env:
          CACHIER_TEST_HOST: ${{ secrets.CACHIER_TEST_HOST  }}
          CACHIER_TEST_DB: ${{ secrets.CACHIER_TEST_DB  }}
          CACHIER_TEST_USERNAME: ${{ secrets.CACHIER_TEST_USERNAME  }}
          CACHIER_TEST_PASSWORD: ${{ secrets.CACHIER_TEST_PASSWORD  }}
          CACHIER_TEST_VS_LIVE_MONGO: ${{ secrets.CACHIER_TEST_VS_LIVE_MONGO  }}
```

If we have the environment key set up properly, but not this `env` part, the job technically has access to the secrets, but not the machine/process running the code.

If we have this part but not the `environment` key, nothing gets forwarded (I'm guessing a bunch of empty environment variables get created), and no authentication can take place, as you can see from the failing tests.
